# Generated by Django 5.1.4 on 2024-12-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='AcademicProjects',
        ),
        migrations.RemoveField(
            model_name='user',
            name='PG',
        ),
        migrations.RemoveField(
            model_name='user',
            name='UG',
        ),
        migrations.RemoveField(
            model_name='user',
            name='XIIth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Xth',
        ),
    ]
